### PR TITLE
feat(SEO): add seo tags

### PR DESCRIPTION
**Pull request by orlando**
**What:** Add SEO tags

**Why:** Closes https://github.com/debtcollective/student-debt-campaign/issues/13

**How:**

- Add SEO component to page

**_SEO preview using metatags.io_**
image

**Notes:**

I'm not connecting this to the CMS yet, there's some work to do in order to make it more usable. Will ask @duranmla how to do this correctly

### CODE REVIEW

**Comment by duranmla** [comment]
@orlando while the new approach looks great I think we may want to remove https://github.com/debtcollective/student-debt-campaign-netlify/blob/od/seo/src/components/Layout.js right? Because it was intended to handle the SEO that we currently have.

**Review by duranmla — CHANGES_REQUESTED** [review]
Check the Layout file I mentioned earlier and make sure to deprecated any previous intended code for SEO before merge this one.

**Comment by orlando** [comment]
@duranmla oh sure, let me remove that, we are putting all these fields in the SEO component

**Comment by orlando** [comment]
@duranmla changes up, please take a look when you can

**Review by duranmla — APPROVED** [review]

**Pull request merged**
